# This is a basic workflow that is manually triggered

name: geotoolpipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./server
        

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/ j
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Backend dependencies
      working-directory: server  # Adjust this folder name if necessary
      run: npm install

    - name: Start or restart project
      working-directory: server  # Adjust this folder name if necessary
      run: |
          if [[ "${{ steps.check-pm2.outputs.is_running }}" == "" ]]; then
            pm2 start server.js --name geotoolbackend
          else
            pm2 restart geotoolbackend
          fi
    - name: Install frontend dependencies
      working-directory: ui
      run: npm install
    - name: build frontend and running pm2
      working-directory: ui      
      run: npm run build
      run: npm run pm2 start pm2.json
#     - run: npm run build --if-present
#     - run: cp /home/vipin/api_v1_ookul/.env /home/vipin/api_v1_ookul/api_v1_work/api_v1/api_v1/.env
#     - run: pm2 restart server.js --name apiv1
#     - run: pm2 restart telgramBot.js --name telebot
