# This is a basic workflow that is manually triggered

name: geotoolpipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./server
        

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/ j
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Backend dependencies
      working-directory: server  # Adjust this folder name if necessary
      run: npm install

    - name: Start or restart project
      working-directory: server  # Adjust this folder name if necessary
      run: pm2 start server.js --name geotoolServer

    - name: Install frontend dependencies
      working-directory: ui
      run: npm install
    - name: build frontend and running pm2
      working-directory: ui      
      run: npm run build --if-present
      run: npm run pm2 start pm2.json geotoolUI